- name: Preflight
  tags: always
  include_tasks: 00-preflight.yml

- name: Install and configure Docker
  tags: docker
  include_tasks: 01-docker.yml

- name: Manage users
  tags: users
  include_tasks: 02-users.yml

- name: Configure system
  tags:
    - packages
    - directories
    - files
    - sysctl
    - limits
  include_tasks: 03-system.yml
