- name: restart systemd-resolved
  systemd_service:
    name: systemd-resolved
    state: restarted

- name: restart docker
  systemd_service:
    name: docker
    state: restarted
    daemon_reload: true

- name: restart dnsmasq
  systemd_service:
    name: dnsmasq
    state: restarted
    daemon_reload: true
