name: "release-please"

on:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      releases-created: ${{ steps.release.outputs.releases_created }}
      release-created: ${{ steps.release.outputs['release_created'] }}
      version: ${{ steps.release.outputs['version'] }}
      tag: ${{ steps.release.outputs['tag_name']}}

    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          command: manifest
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

      - name: Show output from release-please
        if: steps.release.outputs.releases_created
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq

  galaxy:
    if: needs.release-please.outputs.release-created
    runs-on: ubuntu-latest
    needs:
      - release-please

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag }}

      - name: Push to galaxy
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
